# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' E-M haplotyping with a limited number of markers
#' @param genoMat - (n.samples) x (n.variants) matrix of 0,1,2-encoded genotypes
#' @param possibleHaps - (n.haplotypes) x (n.variants) matrix of 0,1-encoded possible haplotypes
#' @param max_iter - maximum number of E-M iterations
#' @param tol - tolerance of relative log-likelihood changes
#' @return A list containing
#'    * hap_freqs : estimated frequencies of possible haplotypes
#'    * records : matrix keeping track of iteration, log-likelihood, and haplotype frequencies
emHaplotyping <- function(genoMat, possibleHaps, max_iter = 100L, tol = 1e-6) {
    .Call(`_bios666r_emHaplotyping`, genoMat, possibleHaps, max_iter, tol)
}

#' Calculate IBS matrix efficiently
#' @param genoMat - (n.variants) x (n.sample) matrix of 0,1,2-encoded genotypes
#' @return A matrix containing IBS matrix (symmetric)
ibsMatrix <- function(genoMat) {
    .Call(`_bios666r_ibsMatrix`, genoMat)
}

